### ISSUE TITLE
Getting Ingress & CustomResourceDefinition is deprecated warnings

### ISSUE THREAD

**Issue by neetumishra262** [Kong/charts#355] opened 2021-04-29 14:16 UTC
Dear Team,

I am using the Kong-2.0.0 chart & kong application 2.4..0-alpine in my production system. I am getting below 2 warnings in AWS EKS 1.19 cluster:

W0326 16:49:13.592816 16004 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0326 16:49:27.441427 16004 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

Please let me know how to resolve it.

**Comment by mflendrich** [comment] 2021-07-14 11:21
Duplicate of #183 

> Please let me know how to resolve it.

@neetumishra262, our choice of Kubernetes API versions now is determined by our will to support as wide a range of Kubernetes versions as possible. This, for some resources, has meant that we used API versions that were the newest in some old K8s versions, and the oldest/deprecated in the newest k8s versions.

Now that we're nearing release of K8s 1.22, we'll upgrade our manifests to those supported by 1.22, which will likely mean a drop of support for older k8s (at least for <1.16 in the most conservative approach).

**Closed as completed by mflendrich** 2021-07-14 11:21 UTC
