### ISSUE TITLE
Kubernetes service for status listener is missing

### ISSUE THREAD

**Issue by michbeck100** [Kong/charts#277] opened 2021-02-12 10:40 UTC
Why does the helm chart not expose the status listener port (default 8100, or 8543 for tls) using a service or even with ingress? Is this on purpose? 
The reason I'm asking it that I want to use the prometheus plugin. With the current setup I can't configure prometheus to connect to the `/metrics` endpoint.

**Comment by mflendrich** [comment] 2021-02-12 11:12
Hi @michbeck100,

> Why does the helm chart not expose the status listener port (default 8100, or 8543 for tls) using a service or even with ingress?

Because this wouldn't work as intended.

Each pod exposing `/metrics` has individual counters. Accessing `/metrics` through a service would return metrics from a random pod with every request, which is incompatible with Prometheus. Instead, Prometheus needs to be configured to discover individual pods, and scrape `/metrics` from each pod independently.

This chart automates pod discovery by means of `ServiceMonitor`, but this requires your Prometheus to be managed by Prometheus Operator. Enabling `ServiceMonitor` in the helm chart (and running Prometheus as operated by Prometheus Operator) is the recommended way forward.

It is possible to integrate without Prometheus Operator, but you'll need to tune pod annotations and Prometheus's `kubernetes_sd_config` manually instead.

Closing this issue for now - please reply if you have further questions.

**Closed as completed by mflendrich** 2021-02-12 11:12 UTC

**Comment by michbeck100** [comment] 2021-02-12 11:21
Thanks for the clarification.

**Comment by zffocussss** [comment] 2022-03-31 16:38
> Hi @michbeck100,
> 
> > Why does the helm chart not expose the status listener port (default 8100, or 8543 for tls) using a service or even with ingress?
> 
> Because this wouldn't work as intended.
> 
> Each pod exposing `/metrics` has individual counters. Accessing `/metrics` through a service would return metrics from a random pod with every request, which is incompatible with Prometheus. Instead, Prometheus needs to be configured to discover individual pods, and scrape `/metrics` from each pod independently.
> 
> This chart automates pod discovery by means of `ServiceMonitor`, but this requires your Prometheus to be managed by Prometheus Operator. Enabling `ServiceMonitor` in the helm chart (and running Prometheus as operated by Prometheus Operator) is the recommended way forward.
> 
> It is possible to integrate without Prometheus Operator, but you'll need to tune pod annotations and Prometheus's `kubernetes_sd_config` manually instead.
> 
> Closing this issue for now - please reply if you have further questions.

serviceMonitor is not useful in the case,as /metrics are accessed by status port which is close to external
