### ISSUE TITLE
coulld not set mtls to gateway

### ISSUE THREAD

**Issue by rookie-fpc** [Kong/charts#1189] opened 2024-12-05 07:22 UTC
gateway.yaml
```
admin:
  enabled: true
  type: ClusterIP
  ClusterIP: None
  annotations: {}
  labels: {}

  http:
    enabled: false

  tls:
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters:
    - http2
    client:
      caBundle: ""
      secretName: "admin-api-ca-cert"
```

get secret
```
[root@iadlnespto2 kong]# kubectl get secret -n kong
NAME                                                    TYPE                DATA   AGE
admin-api-ca-cert                                       kubernetes.io/tls   2      3h56m
```

test helm:
```
[root@iadlnespto2 kong]# helm install kong -n kong  . -f vales1.yaml --dry-run --debug
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
install.go:224: 2024-12-05 15:17:07.091094053 +0800 CST m=+0.030684324 [debug] Original chart version: ""
install.go:241: 2024-12-05 15:17:07.091141774 +0800 CST m=+0.030732042 [debug] CHART PATH: /home/online/kong

install.go:263: 2024-12-05 15:17:07.108286707 +0800 CST m=+0.047876978 [debug] WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
Error: INSTALLATION FAILED: execution error at (kong/templates/service-kong-admin.yaml:95:4): kong/admin-api-ca-cert secret not found
helm.go:86: 2024-12-05 15:17:07.123929914 +0800 CST m=+0.063520181 [debug] execution error at (kong/templates/service-kong-admin.yaml:95:4): kong/admin-api-ca-cert secret not found
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:158
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
        runtime/proc.go:271
runtime.goexit
        runtime/asm_amd64.s:1695
```

why I get this error

**Comment by pmalek** [comment] 2024-12-05 11:55
I have not been able to reproduce that using the provided values and `kong/kong` chart, version `2.44.0`

```
helm upgrade --install --create-namespace -n kong1189 kong --values v_kong_1189.yaml --version 2.44.0 kong/kong
Release "kong" has been upgraded. Happy Helming!
NAME: kong
LAST DEPLOYED: Thu Dec  5 12:45:17 2024
NAMESPACE: kong1189
STATUS: deployed
REVISION: 3
TEST SUITE: None
NOTES:
To connect to Kong, please execute the following commands:

HOST=$(kubectl get svc --namespace kong1189 kong-kong-proxy -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
PORT=$(kubectl get svc --namespace kong1189 kong-kong-proxy -o jsonpath='{.spec.ports[0].port}')
export PROXY_IP=${HOST}:${PORT}
curl $PROXY_IP

Once installed, please follow along the getting started guide to start using
Kong: https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/getting-started/
```

What might be the culprit here is the `--dry-run` flag. I'm also getting this error using it:

```
history.go:56: 2024-12-05 12:47:03.451587 +0100 CET m=+0.120883001 [debug] getting history for release kong
upgrade.go:164: 2024-12-05 12:47:04.679347 +0100 CET m=+1.348638584 [debug] preparing upgrade for kong
Error: UPGRADE FAILED: execution error at (kong/templates/service-kong-admin.yaml:95:4): kong1189/admin-api-ca-cert secret not found
helm.go:86: 2024-12-05 12:47:04.760606 +0100 CET m=+1.429898043 [debug] execution error at (kong/templates/service-kong-admin.yaml:95:4): kong1189/admin-api-ca-cert secret not found
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:243
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
        runtime/proc.go:272
runtime.goexit
        runtime/asm_arm64.s:1223
```

The chart errors out when the secret is not found in https://github.com/Kong/charts/blob/0242f363bbafc576a1f370b9b4220abe0c6a269c/charts/kong/templates/service-kong-admin.yaml#L95 which is a yet another guard rail for users which prevents them from installing the chart when the secret is missing and silently ignoring the error.

Since all of `install`, `upgrade` and `template` lack a flag that would allow users to provide information about existing in cluster objects I'm afraid there's nothing we can do in this cause.

The only possible way forward that I can see is to add a value like `failNonCritical` to prevent `fail`s in templates to cause these failures and wrap each `fail` invocation in a conditional but that feels clunky at best and will be a maintenance nightmare to keep up.

For this reason I'm going to close this issue. Let me know if you have any other comments on this or questions.

**Closed as not planned by pmalek** 2024-12-05 11:55 UTC
