### ISSUE TITLE
Deprecation warnings on helm install

### ISSUE THREAD

**Issue by akira28** [Kong/charts#404] opened 2021-07-14 09:38 UTC
I'm using the latest version of the Kong chart (2.2.0) on a cluster with Kubernetes version 1.19.0 and I'm getting several deprecation warnings:

```
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
rbac.authorization.k8s.io/v1beta1 Role is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 Role
rbac.authorization.k8s.io/v1beta1 RoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 RoleBinding
```

**Comment by mflendrich** [comment] 2021-07-14 11:15
Duplicate of https://github.com/Kong/charts/issues/183

**Closed as completed by mflendrich** 2021-07-14 11:15 UTC
