### ISSUE TITLE
Feature request: Ability to allow for checksums for configMaps

### ISSUE THREAD

**Issue by d19dotca** [Kong/charts#699] opened 2022-12-09 23:39 UTC
A support case was opened earlier with the following feature request:

>We consume the kong-enterprise helm chart as a dependency for use in our environment. We have our own configmap that we define for kong.yml and specify as such in dblessConfig.configMap.
>
>The problem is that currently, you helm chart only changes the checksum annotation for the deployment when the contents of dblessConfig.config changes: https://github.com/Kong/charts/blob/main/charts/kong/templates/deployment.yaml#L49
>
>Can you please provide a mechanism or work-around so that we can get that checksum to change based on the contents of the configmap that we provide ourselves as described above?

It'd be great if this could be considered in a future release of our Helm charts.

**Comment by mflendrich** [comment] 2023-01-31 17:21
Duplicate of https://github.com/Kong/charts/issues/217

**Comment by pmalek** [comment] 2023-01-31 17:40
@d19dotca 👋 

Have you considered using an off the shelf tool like [Reloader](https://github.com/stakater/Reloader) as suggested in here: https://github.com/Kong/charts/issues/217#issuecomment-1082962041?

**Comment by d19dotca** [comment] 2023-01-31 18:13
This was simply filed on behalf of a customer (I'm with Kong 😄), so it's not for me specifically. I believe I had provided them with those recommendations though from what I saw in another thread in Slack somewhere. 

I suppose we can close this out as a duplicate of the other ticket if it's indeed the same thing. I must have missed that earlier. Sorry for the duplicate.

**Comment by pmalek** [comment] 2023-02-01 10:52
No worries. I'm closing this in favor of #217 but as suggested there: this should really be solved by a tool like Reloader rather than providing a bespoke mechanism within the helm chart itself.

As I think of it I'm not even sure if there is a mechanism to access a ConfigMap or a Secret from helm to check its annotations/contents during upgrade/install 🤔 .

**Closed as completed by pmalek** 2023-02-01 10:52 UTC
